# Generated by Django 2.2.2 on 2019-06-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('nos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Fake1', models.FloatField()),
                ('Fake2', models.FloatField()),
                ('Fake3', models.FloatField()),
                ('id_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Random')),
            ],
        ),
    ]
