# Generated by Django 2.2.2 on 2019-06-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190627_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Result',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
